package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"errors"
	"github.com/hatjwe/soar-client/log"
	"go.uber.org/zap"
	"io/ioutil"
	"net"
	"net/http"
	"strings"
)

type SoarClient interface {
	ConventJson() (string, error)
	AddBlockIp(BlockedIps string) SoarClient
	UrlSet(host, path string)
	HeaderSet(key, value string)
	SentHttps() (string, error)
	GetBlockIps() SoarClient
	CheckIp(BlockedIps string) bool
}

// BlockIP 结构体
type BlockIP struct {
	AttackIP []string `json:"attack_ip"`
}
type Soar struct {
	// URL is the base URL of the upstream server
	URL string
	//
	Methon string
	// AuthInfo is for authentication
	Body    string
	BlockIp BlockIP
	Header  map[string]string
}

// New creates a new harbor API HTTP client.
func New() *Soar {
	cli := new(Soar)
	return cli
}
func (soar *Soar) CheckIp(BlockedIps string) bool {

	ip := net.ParseIP(BlockedIps)
	if ip == nil {
		log.Logger.Error("IP地址解析错误,", zap.String(BlockedIps, "不是有效ip,已忽略继续解析下边ip"))
		return false
	}

	return true
}
func (soar *Soar) AddBlockIp(BlockedIps string) SoarClient {
	if soar.CheckIp(BlockedIps) {
		soar.BlockIp.AttackIP = append(soar.BlockIp.AttackIP, BlockedIps)
	}

	return soar
}
func (soar *Soar) GetBlockIps() SoarClient {
	return soar
}
func (soar *Soar) UrlSet(host, apipath string) {

	soar.URL = host + apipath

}
func (soar *Soar) HeaderSet(key, value string) {
	soar.Header[key] = value

}
func (soar *Soar) BodySet(data string) {

	soar.Body = data

}
func (soar *Soar) ConventJson() (string, error) {

	if soar.BlockIp.AttackIP == nil {
		log.Logger.Error("未设置封禁ip数据转换失败")
	}
	jsonData, err := json.Marshal(soar.BlockIp.AttackIP)
	if err != nil {
		log.Logger.Error("转换为 JSON 失败:", zap.Error(err))

		return "", err
	}
	return string(jsonData), err

}
func (soar *Soar) SentHttps() (string, error) {
	if soar.Methon == "" || soar.URL == "" {
		return "", errors.New("Methon或url设置为空")
	}
	body := strings.NewReader(soar.Body)
	request, err := http.NewRequest(soar.Methon, soar.URL, body)
	if err != nil {
		return "", err
	}
	if soar.Header != nil {
		for key, value := range soar.Header {
			request.Header.Set(key, value)
		}

	}
	client := &http.Client{}
	response, err := client.Do(request)
	if err != nil {
		return "", err
	}

	defer response.Body.Close()
	bodystr, err := ioutil.ReadAll(response.Body)
	if err != nil {
		return "", err
	}
	log.Logger.Info("响应包信息", zap.String("body", string(bodystr)), zap.String("url", soar.URL))
	return string(bodystr), nil
}
